# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /npmap/bootstrap/3.3.2
url:              http://www.nps.gov/npmap/bootstrap/3.3.2/
encoding:         UTF-8

# Custom vars
current_version:  3.3.2
repo:             https://github.com/nationalparkservice/bootstrap
sass_repo:        

download:
  source:         
  dist:           
  sass:           

blog:             http://www.nps.gov/npmap/blog/
expo:             

cdn:
  css:            http://www.nps.gov/lib/bootstrap/3.3.2/css/nps-bootstrap.min.css
  css_theme:      http://www.nps.gov/lib/bootstrap/3.3.2/css/nps-bootstrap-theme.min.css
  js:             http://www.nps.gov/lib/bootstrap/3.3.2/js/nps-bootstrap.min.js
