# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
repo:             https://github.com/nationalparkservice/bootstrap
download:         https://github.com/nationalparkservice/bootstrap/archive/v3.0.0.zip
download_dist:    https://github.com/nationalparkservice/bootstrap/releases/download/v3.0.0/nps-bootstrap-3.0.0-dist.zip

blog:             http://www.nps.gov/npmap/blog

cdn_css:          http://www.nps.gov/npmap/tools/bootstrap/3.0.0/css/nps-bootstrap.min.css
cdn_theme_css:    http://www.nps.gov/npmap/tools/bootstrap/3.0.0/css/nps-bootstrap-theme.min.css
cdn_js:           http://www.nps.gov/npmap/tools/bootstrap/3.0.0/js/nps-bootstrap.min.js
