# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /npmap/tools/bootstrap
url:              https://www.nps.gov/npmap/tools/bootstrap
encoding:         UTF-8

# Custom vars
current_version:  3.3.2
repo:             https://github.com/nationalparkservice/bootstrap
sass_repo:        

download:
  source:         
  dist:           
  sass:           

blog:             https://www.nps.gov/npmap/blog
expo:             

cdn:
  css:            https://www.nps.gov/lib/bootstrap/3.3.2/css/nps-bootstrap.min.css
  css_theme:      https://www.nps.gov/lib/bootstrap/3.3.2/css/nps-bootstrap-theme.min.css
  js:             https://www.nps.gov/lib/bootstrap/3.3.2/js/nps-bootstrap.min.js
